"""cascade delete user role

Revision ID: 84e8a6af9598
Revises: 02a9015f9e23
Create Date: 2025-06-02 15:48:58.750967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '84e8a6af9598'
down_revision: Union[str, None] = '02a9015f9e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_user_role_role_id_fkey', 'auth_user_role', type_='foreignkey')
    op.drop_constraint('auth_user_role_user_id_fkey', 'auth_user_role', type_='foreignkey')
    op.create_foreign_key(None, 'auth_user_role', 'auth_role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'auth_user_role', 'auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_user_role_role_id_fkey', 'auth_user_role', type_='foreignkey')
    op.drop_constraint('auth_user_role_user_id_fkey', 'auth_user_role', type_='foreignkey')
    op.create_foreign_key('auth_user_role_user_id_fkey', 'auth_user_role', 'auth_user', ['user_id'], ['id'])
    op.create_foreign_key('auth_user_role_role_id_fkey', 'auth_user_role', 'auth_role', ['role_id'], ['id'])
    # ### end Alembic commands ###
