"""Add app user (user profile) model

Revision ID: a96780850e0b
Revises: 84e8a6af9598
Create Date: 2025-06-12 00:46:13.074775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'a96780850e0b'
down_revision: Union[str, None] = '84e8a6af9598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_user_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', name='activitylevel'), nullable=False),
    sa.Column('health_goal', sa.Enum('weight_loss', 'muscle_gain', 'maintenance', name='healthgoal'), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id')
    )
    op.create_index(op.f('ix_app_user_first_name'), 'app_user', ['first_name'], unique=False)
    op.create_index(op.f('ix_app_user_last_name'), 'app_user', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_last_name'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_first_name'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
