name: Kalorie-Tracker Test CI

on:
  push:
    branches: [main]
    paths-ignore: ["**.md", "migrations"]
  pull_request:
    paths-ignore: ["**.md", "migrations"]
  workflow_dispatch:

jobs:
  test:
    name: Test the application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.11"
        cache: "poetry"
    
    - name: Install Poetry via pipx
      run: |
        pipx ensurepath
        pipx install poetry --python "${{ steps.python.outputs.python-path }}"

    - name: Install dependencies
      run: |
        poetry env use ${{ steps.python.outputs.python-version }}
        poetry install --no-interaction
    - name: Run tests
      run: poetry run pytest tests/ --verbose
