name: Kalorie-Tracker Test CI

on:
  push:
    branches: [main]
    paths-ignore: ["**.md", "migrations"]
  pull_request:
    paths-ignore: ["**.md", "migrations"]
  workflow_dispatch:

jobs:
  test:
    name: Test the application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
        exec bash -l
        pipx install poetry
        poetry install
    - name: Run tests
      run: pytest tests/ --verbose
